#Site settings
title: 路易斯·李的主页
email: louislee92@163.com
description: "欢迎来到路易斯·李的主页！"
baseurl: "/louislee92.github.com"
url: "http://louislee92.github.com"

# Build settings
markdown: kramdown
permalink: pretty
