# Site settings
title: 路易斯.李的专栏
email: louislee92@163.com
description: > # this means to ignore newlines until "baseurl:"
  THIS IS LOUIS LEE'S PAGE!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: louislee92
github_username:  louislee92

# Build settings
markdown: kramdown
